### ISSUE TITLE
Update LHCbDirac version for 6.1.19

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/lhcbsetupproject#4]
@milliams Can you let me know when you plan to run the LHCb tests so I can bump the version of LHCbDirac in the repo. Alternatively if you could do it as part of the release testing that would be great :)

Thanks,

Rob

**Comment by milliams** [comment]
I'm about to run the LHCb tests now. Do you need to bump the version first? If so, let me know when it's done.

**Comment by milliams** [comment]
@rob-c I'm currently waiting on this for running the LHCb tests. Should I just go ahead and start the tests?

**Comment by rob-c** [comment]
Give me about 20min something came up, I just want to bump to the most recent lhcb release to be good citizens as part of the release.

**Comment by milliams** [comment]
No worries, poke me when it's done.

**Comment by rob-c** [comment]
Think I've updated it to v8r2p36 in both master and testing, if you get a chance can you confirm the change is picked up. Thanks :+1:

**Comment by milliams** [comment]
It printed

```
INFO     Storing new LHCbDirac environment (v8r2p36:x86_64-slc6-gcc49-opt)
```

on startup of the tests so I think it's good.
